### ISSUE TITLE
Missing documentation to switch Cybersource from Sandbox to Production

### ISSUE THREAD

**Issue by diegoag64** [overhangio/tutor-ecommerce#29]
Documentation is missing a very important config value to switch Cybersource from sandbox to production.

The config key is the following: flex_run_environment
For Sandbox this is as default set to 'cybersource.environment.sandbox', and to switch to production this has to be changed set in the config to 'cybersource.environment.production'

I tested this since I am about to push my website to production and just got approved by Cybersource to use a live account, but it kept not working because this is not specified in the docs which was odd for me in the first place.

So I propose we change this:
```    
cybersource:
    merchant_id: SET-ME-PLEASE 
    flex_shared_secret_key_id: SET-ME-PLEASE
    flex_shared_secret_key: SET-ME-PLEASE
    soap_api_url: https://ics2wstest.ic3.com/commerce/1.x/transactionProcessor/CyberSourceTransaction_1.140.wsdl
    transaction_key: SET-ME-PLEASE
paypal:
    cancel_checkout_path: /checkout/cancel-checkout/
    client_id: SET-ME-PLEASE
    client_secret: SET-ME-PLEASE
    error_url: /checkout/error/
    mode: sandbox
    receipt_url: /checkout/receipt/
```

To this:
```    
cybersource:
    merchant_id: SET-ME-PLEASE 
    flex_shared_secret_key_id: SET-ME-PLEASE
    flex_shared_secret_key: SET-ME-PLEASE
    soap_api_url: https://ics2wstest.ic3.com/commerce/1.x/transactionProcessor/CyberSourceTransaction_1.140.wsdl
    transaction_key: SET-ME-PLEASE
    flex_run_environment: [set as 'cybersource.environment.sandbox' as default, change to 'cybersource.environment.production' for use in production]
paypal:
    cancel_checkout_path: /checkout/cancel-checkout/
    client_id: SET-ME-PLEASE
    client_secret: SET-ME-PLEASE
    error_url: /checkout/error/
    mode: sandbox
    receipt_url: /checkout/receipt/```
